/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/soQ9NSx5gEs
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import scraper from "google-play-scraper";
import { ListItem } from "./ListItem";
import checkApp from "@/actions/checkApp";
import downloadApp from "@/actions/downloadApp";
import unzipApp from "@/actions/unzipApp";

export async function List({ term }: { term: string }) {
  const apps = await scraper.search({ term, num: 3 });

  if (!apps.length) {
    return (
      <div className="w-full max-w-3xl px-4">
        <ul className="grid grid-cols-1 gap-4" />
        <div
          className={`bg-white rounded-lg shadow-md dark:bg-gray-800 p-8 flex flex-col items-center justify-center ${
            false ? "hidden" : "flex"
          }`}
        >
          <FrownIcon className="w-12 h-12 text-gray-500 dark:text-gray-400" />
          <h3 className="mt-4 text-xl font-bold text-gray-800 dark:text-gray-200">
            No apps found
          </h3>
          <p className="mt-2 text-gray-600 dark:text-gray-400 text-center">
            It looks like there are no apps matching your search. Try searching
            for something else.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="w-full max-w-3xl px-4">
      <ul className="grid grid-cols-1 gap-4">
        {apps.map(({ appId, title, icon, scoreText, developer }) => (
          <ListItem
            key={appId}
            appId={appId}
            title={title}
            icon={icon}
            scoreText={scoreText}
            developer={developer}
            downloadApp={downloadApp}
            unzipApp={unzipApp}
            checkApp={checkApp}
          />
        ))}
      </ul>
    </div>
  );
}

function FrownIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M16 16s-1.5-2-4-2-4 2-4 2" />
      <line x1="9" x2="9.01" y1="9" y2="9" />
      <line x1="15" x2="15.01" y1="9" y2="9" />
    </svg>
  );
}
